In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from tensorflow import keras

In [ ]:
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential, load_model

In [ ]:
data = pd.read_csv("train.csv")

In [ ]:
data.head

NameError: name 'data' is not defined

In [ ]:
data.shape

(891, 12)

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
data.drop(columns = ['Cabin'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
emb_mode = data['Embarked'].mode()

In [ ]:
data['Embarked'].fillna(emb_mode, inplace = True)

In [ ]:
age_mean = data['Age'].mean()

In [ ]:
data['Embarked'].fillna(1, inplace = True)

In [ ]:
data.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [ ]:
replacement_dict = {
    'male': 1,
    'female': 0
}
# Replace values in the 'Category' column using the dictionary
data['Sex'] = data['Sex'].replace(replacement_dict)

In [ ]:
replace_dict = {
    'Q': 2,
    'S': 1,
    'C': 0
}
# Replace values in the 'Category' column using the dictionary
data['Embarked'] = data['Embarked'].replace(replace_dict)

In [ ]:
data['Age'].fillna(29.699118, inplace = True)

In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,0.647587,29.699118,0.523008,0.381594,32.204208,0.897868
std,257.353842,0.486592,0.836071,0.477990,13.002015,1.102743,0.806057,49.693429,0.514624
min,1.000000,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,0.000000,22.000000,0.000000,0.000000,7.910400,1.000000
50%,446.000000,0.000000,3.000000,1.000000,29.699118,0.000000,0.000000,14.454200,1.000000
75%,668.500000,1.000000,3.000000,1.000000,35.000000,1.000000,0.000000,31.000000,1.000000
max,891.000000,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200,2.000000

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,1
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,1

In [ ]:
data.corr(method = 'pearson')

<ipython-input-19-8189ca41251e>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr(method = 'pearson')

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
PassengerId,1.000000,-0.005007,-0.035144,0.042939,0.033207,-0.057527,-0.001652,0.012658,-0.017443
Survived,-0.005007,1.000000,-0.338481,-0.543351,-0.069809,-0.035322,0.081629,0.257307,-0.125953
Pclass,-0.035144,-0.338481,1.000000,0.131900,-0.331339,0.083081,0.018443,-0.549500,0.305762
Sex,0.042939,-0.543351,0.131900,1.000000,0.084153,-0.114631,-0.245489,-0.182333,0.022521
Age,0.033207,-0.069809,-0.331339,0.084153,1.000000,-0.232625,-0.179191,0.091566,-0.031924
SibSp,-0.057527,-0.035322,0.083081,-0.114631,-0.232625,1.000000,0.414838,0.159651,0.030874
Parch,-0.001652,0.081629,0.018443,-0.245489,-0.179191,0.414838,1.000000,0.216225,-0.035957
Fare,0.012658,0.257307,-0.549500,-0.182333,0.091566,0.159651,0.216225,1.000000,-0.268865
Embarked,-0.017443,-0.125953,0.305762,0.022521,-0.031924,0.030874,-0.035957,-0.268865,1.000000

In [ ]:
data['Fare'] = data['Fare'] / 512.329200

In [ ]:
data['Age'] = data['Age'] / 80

In [ ]:
data['Parch'] = data['Parch'] / 6

In [ ]:
data = data.drop(columns = ['Name'])

In [ ]:
data = data.dropna(subset = ['Embarked'])

In [ ]:
data = data.drop(columns = "Ticket", axis = 1)
data = data.drop(columns = "Cabin", axis = 1)

In [ ]:
from sklearn.utils import resample

survived = data[data['Survived'] == '0']
died = data[data['Survived'] == '1']

# Upsample class B to match the number of rows in class A
class_B_upsampled = resample(died, replace=True, n_samples = 549, random_state=42)

# Combine the upsampled class B with class A
data = pd.concat([survived, class_B_upsampled])

# Shuffle the DataFrame to mix the rows
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

ValueError: ignored

In [ ]:
dependent = pd.DataFrame(data["Survived"])

In [ ]:
independent = data.drop(columns = "Survived")

In [ ]:
model = Sequential ([
     tf.keras.layers.Dense(7, activation = 'relu', name = 'L1'),
     tf.keras.layers.Dense(16, activation = 'relu', name = 'L2'),
     tf.keras.layers.Dense(1, activation = 'sigmoid', name = 'L3')
])

In [ ]:
independent = np.asarray(independent).astype(np.float32)
dependent = np.asarray(dependent).astype(np.float32)

In [ ]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
    metrics = ['accuracy']
)

model.fit(
    independent, dependent,
    epochs = 60, batch_size = 32
)

Epoch 1/60
28/28 [==============================] - 1s 4ms/step - loss: 24.0064 - accuracy: 0.4994
Epoch 2/60
28/28 [==============================] - 0s 4ms/step - loss: 1.3293 - accuracy: 0.5421
Epoch 3/60
28/28 [==============================] - 0s 3ms/step - loss: 0.7305 - accuracy: 0.5713
Epoch 4/60
28/28 [==============================] - 0s 3ms/step - loss: 0.6863 - accuracy: 0.6027
Epoch 5/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6761 - accuracy: 0.6105
Epoch 6/60
28/28 [==============================] - 0s 2ms/step - loss: 0.8399 - accuracy: 0.5567
Epoch 7/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6487 - accuracy: 0.6173
Epoch 8/60
28/28 [==============================] - 0s 2ms/step - loss: 0.7133 - accuracy: 0.6004
Epoch 9/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6680 - accuracy: 0.6004
Epoch 10/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6491 - accuracy: 0.6072
Epoch 11/60
28/28 [==============================] - 0s 2ms/step - loss: 0.7618 - accuracy: 0.6162
Epoch 12/60
28/28 [==============================] - 0s 2ms/step - loss: 0.7316 - accuracy: 0.5993
Epoch 13/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6203 - accuracy: 0.6678
Epoch 14/60
28/28 [==============================] - 0s 2ms/step - loss: 0.8261 - accuracy: 0.5971
Epoch 15/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6609 - accuracy: 0.6644
Epoch 16/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6395 - accuracy: 0.6431
Epoch 17/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6669 - accuracy: 0.6498
Epoch 18/60
28/28 [==============================] - 0s 2ms/step - loss: 0.6329 - accuracy: 0.6498
Epoch 19/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5716 - accuracy: 0.7127
Epoch 20/60
28/28 [==============================] - 0s 3ms/step - loss: 0.6727 - accuracy: 0.6341
Epoch 21/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5504 - accuracy: 0.7452
Epoch 22/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5538 - accuracy: 0.7228
Epoch 23/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5607 - accuracy: 0.7205
Epoch 24/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5641 - accuracy: 0.7273
Epoch 25/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.7800
Epoch 26/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5322 - accuracy: 0.7609
Epoch 27/60
28/28 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 0.7609
Epoch 28/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5560 - accuracy: 0.7363
Epoch 29/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5214 - accuracy: 0.7632
Epoch 30/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5005 - accuracy: 0.7666
Epoch 31/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4960 - accuracy: 0.7834
Epoch 32/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5004 - accuracy: 0.7744
Epoch 33/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5808 - accuracy: 0.7262
Epoch 34/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5216 - accuracy: 0.7576
Epoch 35/60
28/28 [==============================] - 0s 4ms/step - loss: 0.5719 - accuracy: 0.7205
Epoch 36/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5254 - accuracy: 0.7497
Epoch 37/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5064 - accuracy: 0.7834
Epoch 38/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4889 - accuracy: 0.7811
Epoch 39/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4853 - accuracy: 0.7823
Epoch 40/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4968 - accuracy: 0.7957
Epoch 41/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5855 - accuracy: 0.7318
Epoch 42/60
28/28 [==============================] - 0s 3ms/step - loss: 0.6093 - accuracy: 0.7205
Epoch 43/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5396 - accuracy: 0.7396
Epoch 44/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5196 - accuracy: 0.7621
Epoch 45/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5107 - accuracy: 0.7632
Epoch 46/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5086 - accuracy: 0.7666
Epoch 47/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4940 - accuracy: 0.7778
Epoch 48/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4745 - accuracy: 0.7924
Epoch 49/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5128 - accuracy: 0.7643
Epoch 50/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4996 - accuracy: 0.7823
Epoch 51/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4827 - accuracy: 0.7924
Epoch 52/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4683 - accuracy: 0.7946
Epoch 53/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5090 - accuracy: 0.7767
Epoch 54/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4881 - accuracy: 0.7935
Epoch 55/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5095 - accuracy: 0.7677
Epoch 56/60
28/28 [==============================] - 0s 4ms/step - loss: 0.5321 - accuracy: 0.7621
Epoch 57/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5887 - accuracy: 0.7172
Epoch 58/60
28/28 [==============================] - 0s 3ms/step - loss: 0.5119 - accuracy: 0.7710
Epoch 59/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4827 - accuracy: 0.7856
Epoch 60/60
28/28 [==============================] - 0s 3ms/step - loss: 0.4670 - accuracy: 0.7879